name: C++ Test Workflow

on:
  workflow_dispatch:  # Uruchomienie workflow ręcznie z GitHub UI

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt 6 and tools
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev cmake build-essential

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
