name: C++ Test Workflow

on:
  workflow_dispatch:  # Uruchomienie workflow ręcznie z GitHub UI

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt and dependencies
        run: |
          choco install qt6 --installargs 'ADD_TO_PATH=YES'  # Używamy Chocolatey do zainstalowania Qt6

      - name: Set up CMake
        uses: actions/setup-cmake@v2  

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          ./tests/test_task  # Upewnij się, że plik testowy jest poprawny

